version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            - echo Build started on `date`
    pre_build:
        commands:
            #Run unit test
          - echo Build started on `date`
    build:
        commands:
          - echo Build completed on `date`
            
    post_build:
        commands:
          - echo Build completed on `date`

artifacts:
    type: zip
    files:
      - '**/*'